[package]
name = "actix-redisactor"
version = "0.1.1"
authors = ["Hui Tang <duriantang@gmail.com>"]
edition = "2018"

[dependencies]
redis-async = "~0.4.5"
derive_more = "~0.15.0"
log = "~0.4.6"
actix = "~0.8.3"
tokio-codec = "~0.1.1"
tokio-tcp = "~0.1.3"
backoff = "~0.1.5"
futures = "~0.1.27"
tokio-io = "~0.1.12"
